services:

  # PostgreSQL Database for local development
  postgres:
    image: postgres:14
    container_name: pos_postgres
    ports:
      - "7432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: pos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: